version: 2

jobs:
  auth:
    working_directory: ~/P2P_lending/auth
    docker:
      - image: circleci/node:10
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout:
          path: ~/P2P_lending
      - run:
          name: install npm
          command: npm install
      - run:
          name: push container to docker hub
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && \
            docker build -t $DOCKER_USERNAME/p2p-auth-service:$CIRCLE_SHA1 . && \
            docker push $DOCKER_USERNAME/p2p-auth-service:$CIRCLE_SHA1
      - run:
          name: push container to docker hub (latest)
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && \
            docker build -t $DOCKER_USERNAME/p2p-auth-service . && \
            docker push $DOCKER_USERNAME/p2p-auth-service

  frontend:
    working_directory: ~/P2P_lending/view
    docker:
      - image: circleci/node:10
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout:
          path: ~/P2P_lending
      - run:
          name: install npm
          command: npm install
      - run:
          name: push container to docker hub
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && \
            docker build -t $DOCKER_USERNAME/p2p-frontend-service:$CIRCLE_SHA1 . && \
            docker push $DOCKER_USERNAME/p2p-frontend-service:$CIRCLE_SHA1
      - run:
          name: push container to docker hub (latest)
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && \
            docker build -t $DOCKER_USERNAME/p2p-frontend-service . && \
            docker push $DOCKER_USERNAME/p2p-frontend-service
      - run:
          name: build react
          command: npm run build
      
      - run:
            name: Firebase Deploy
            command: ls -a && ./node_modules/.bin/firebase deploy --project $PROJECT_ID --token "$TOKEN_FIREBASE"
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "92:94:37:e7:f7:4c:f9:51:a7:3c:97:1f:c2:89:15:18"
      - run:
          name: Deploy Over SSH
          command: |
            ssh -o "StrictHostKeyChecking=no" ${SSH_USER}@${SSH_HOST} "\
            docker-compose pull auth && \
            docker-compose up -d"

workflows:
  version: 2
  deploy:
    jobs:
          - auth:
              filters:
                branches:
                  only:
                    - pre-master
          - frontend:
              filters:
                branches:
                  only:
                    - pre-master
          - deploy:
              filters:
                branches:
                  only:
                    - pre-master
              requires:
                - auth
