version: 2

jobs:
  auth:
    working_directory: ~/P2P_lending/auth
    docker:
      - image: circleci/node:10
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout:
          path: ~/P2P_lending
      - run:
          name: install npm
          command: npm install
      - run:
          name: push container to docker hub
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && \
            docker build -t $DOCKER_USERNAME/p2p-auth-service:$CIRCLE_SHA1 . && \
            docker push $DOCKER_USERNAME/p2p-auth-service:$CIRCLE_SHA1
      - run:
          name: push container to docker hub (latest)
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && \
            docker build -t $DOCKER_USERNAME/p2p-auth-service . && \
            docker push $DOCKER_USERNAME/p2p-auth-service

  frontend:
    working_directory: ~/P2P_lending/view
    docker:
      - image: circleci/node:10
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout:
          path: ~/P2P_lending
      - run:
          name: install npm
          command: npm install
      - run:
          name: push container to docker hub
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && \
            docker build -t $DOCKER_USERNAME/p2p-frontend-service:$CIRCLE_SHA1 . && \
            docker push $DOCKER_USERNAME/p2p-frontend-service:$CIRCLE_SHA1
      - run:
          name: push container to docker hub (latest)
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && \
            docker build -t $DOCKER_USERNAME/p2p-frontend-service . && \
            docker push $DOCKER_USERNAME/p2p-frontend-service
      - run:
          name: build react
          command: npm run build
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b0:13:66:5f:1f:31:30:3a:0f:82:e6:0d:ba:ad:04:2e"
      - run:
          name: Deploy Over SSH
          command: |
            ssh -o "StrictHostKeyChecking=no" ${SSH_USER}@${SSH_HOST} "\
            cd P2P_lending && cd docker && \
            sudo docker-compose stop && \
            sudo git pull && \
            sudo docker-compose rm -f && \
            sudo docker-compose pull && \
            sudo docker-compose build nginx && \
            sudo docker-compose up -d && \
            sudo docker-compose restart api && \
            sudo docker image prune -f"

workflows:
  version: 2
  deploy:
    jobs:
      - auth:
          filters:
            branches:
              only:
                - pre-master
      - frontend:
          filters:
            branches:
              only:
                - pre-master
      - deploy:
          filters:
            branches:
              only:
                - pre-master
          requires:
            - auth
            - frontend
