version: 2

jobs:
  auth:
    working_directory: ~/P2P_lending/auth
    docker:
      - image: circleci/node:10
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout:
          path: ~/P2P_lending/auth
      - run:
          name: install npm
          command: npm install
      - run:
          name: push container to docker hub
          command: |
            .

workflows:
  version: 2
  deploy:
    jobs:
          - auth:
              filters:
                branches:
                  only:
                    - pre-master
