version: "3"

services:
  nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: always
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: example
  api:
    restart: always
    # image: startmt/p2p-auth-service:latest
    build:
      context: ../auth
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:3000:3000
    environment:
      - MYSQL_HOST=mysql
      - REDIS_HOST=redis_auth
      - MINIO_ENDPOINT=minio1
      - MINIO_PORT=9000

    depends_on:
      - redis_auth
      - mysql
      - minio1
  redis_auth:
    image: redis:5-alpine
  web:
    # image: startmt/p2p-frontend-service:latest
    build:
      context: ../view
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:8000:8000
    environment:
      - AUTH_SERVICE=http://127.0.0.1/auth
    depends_on:
      - api
  minio1:
    image: minio/minio:RELEASE.2020-02-07T23-28-16Z

    volumes:
      - ./storage:/data1
    ports:
      - "127.0.0.1:9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
